In [1]:
import pandas as pd
import numpy as np
from pareto import ParetoOptimizer

In [3]:
# if __name__ == "__main__":

#     costs = pd.DataFrame([[0.84, 0.72], [0.82, 0.71], [0.83, 0.74], [0.80,0.80]],  
#                          columns=["cost_1", "value_1"])
#     display(costs)

#     optimizer = ParetoOptimizer()
#     optimizer.set_inputs(costs, ["min", "max"])

#     pareto_set = optimizer.optimize()  
#     print(pareto_set)

In [4]:
import pandas as pd 

costs = pd.DataFrame([[4, 2], [2, 1], [3, 4]], columns=["cost", "revenue"])

# Minimization case
optimizer = ParetoOptimizer()
optimizer.set_inputs(costs, optimize_for="min")
optimizer.toggle_objective("revenue") # Maximize revenue

pareto_min = optimizer.optimize()
print(pareto_min)

# Maximization case
optimizer.set_inputs(costs, optimize_for="max") 

pareto_max = optimizer.optimize()
print(pareto_max)

TypeError: 'NoneType' object is not subscriptable

In [5]:
import numpy as np

def is_dominated(obj1, obj2):
    """Check if obj1 dominates obj2"""
    dominates = False
    for a, b in zip(obj1, obj2):
        if a > b:
            dominates = True
            break
    return dominates
    

def get_pareto_front(objectives, mode='minimize'):
    """Compute Pareto front from objectives"""
    pareto_points = []
    
    if mode == 'minimize':
        for obj1 in objectives:
            is_optimal = True
            for obj2 in objectives:
                if is_dominated(obj2, obj1):
                    is_optimal = False
                    break
            if is_optimal:
                pareto_points.append(obj1)
                
    elif mode == 'maximize':
        inverted = -objectives
        pareto_points = get_pareto_front(inverted, mode='minimize')
        pareto_points = -np.array(pareto_points)
        
    return pareto_points
    
    
def multiobjective_optimize(data, mode='minimize'):
    """Find Pareto optimal set from multiobjective data""" 

    objectives = data[:,:-1]
    
    pareto_front = get_pareto_front(objectives, mode)
        
    return pareto_front

In [6]:
# Sample data with 2 objectives 
data = np.array([[1, 2], 
                 [2, 1],
                 [3, 4],
                 [4, 3],
                 [5, 5]])
data

array([[1, 2],
       [2, 1],
       [3, 4],
       [4, 3],
       [5, 5]])

In [7]:
# Get Pareto front minimizing objectives                
pareto_set = multiobjective_optimize(data, mode='minimize')

print(pareto_set)
# [[1 2]
#  [2 1]]

# Get Pareto front maximizing objectives
pareto_set = multiobjective_optimize(data, mode='maximize') 

print(pareto_set)
# [[5 5]
#  [3 4]]

[array([5])]
[[1]]


In [8]:
pareto_set

array([[1]])

In [9]:
import numpy as np
import pandas as pd

class ParetoOptimizationLibrary:
    def __init__(self, data):
        self.data = data
        self.num_objectives = None
        self.objectives = None
        self.pareto_front = []

    def set_objectives(self, objectives):
        """
        Set the objectives for optimization.
        Args:
            objectives (list of functions): List of objective functions.
        """
        self.objectives = objectives
        self.num_objectives = len(objectives)

    def optimize(self, objective_type='minimization'):
        """
        Perform Pareto optimization.
        Args:
            objective_type (str): 'minimization' or 'maximization'.
        Returns:
            List of Pareto-optimal solutions.
        """
        if self.num_objectives is None or self.objectives is None:
            raise ValueError("Objectives not set. Use set_objectives() to define objectives.")

        if objective_type not in ['minimization', 'maximization']:
            raise ValueError("Invalid objective_type. Use 'minimization' or 'maximization'.")

        # Implement optimization algorithm based on objective_type
        if objective_type == 'minimization':
            pareto_solutions = self._minimization_optimization()
        else:
            pareto_solutions = self._maximization_optimization()

        self.pareto_front = pareto_solutions
        return pareto_solutions

    def _minimization_optimization(self):
        # Implement minimization optimization algorithm (e.g., NSGA-II)
        # Populate pareto_solutions with non-dominated solutions
        pareto_solutions = []

        return pareto_solutions

    def _maximization_optimization(self):
        # Implement maximization optimization algorithm (e.g., SPEA2)
        # Populate pareto_solutions with non-dominated solutions
        pareto_solutions = []

        return pareto_solutions



In [10]:

# Example usage:
if __name__ == "__main__":
    # Sample data (replace with your own)
    data = np.random.rand(100, 2)
    df = pd.DataFrame(data, columns=['Objective1', 'Objective2'])

    # Create the library instance
    pareto_optimizer = ParetoOptimizationLibrary(df)

    # Define objective functions (customize these)
    def objective1(data):
        return data['Objective1']

    def objective2(data):
        return data['Objective2']

    pareto_optimizer.set_objectives([objective1, objective2])

    # Perform minimization Pareto optimization
    pareto_front = pareto_optimizer.optimize(objective_type='minimization')

    # Print the Pareto front
    print("Pareto Front:")
    for solution in pareto_front:
        print(solution)

Pareto Front:


In [12]:
pareto_front

[]